const portfolio = [
  {
    id: "1",
    title: "Workable",
    description: "A board where users create, save or search for jobs ",
    img: "/images/workable_home.JPG",
    liveUrl: null,
    code: "https://github.com/MHassan47/Workable",
    keyword: ["React", "TypeScript", "GraphQL", "Node.js", "PostgreSQL"],
  },
  {
    id: "2",
    title: "Budget App",
    description: "A budgeting app that lets users track their finances",
    img: "/images/budget_dashboard.JPG",
    liveUrl: null,
    code: "https://github.com/MHassan47/Budget-App",
    keyword: ["React", "MongoDB", "Redux", "Nodejs", "MUI"],
  },
  {
    id: "3",
    title: "Produc_Div",
    description: "Collaborative productivity management app",
    img: "/images/dashboard.PNG",
    code: "https://github.com/MHassan47/Produc_Div",
    liveUrl: null,
    keyword: ["React", "PostgreSQL", "Express.js", "WebSocket"],
  },
  {
    id: "4",
    title: "Scheduler",
    description: "Real-Time interview scheduler",
    img: "/images/mainpage.png",
    code: "https://github.com/MHassan47/Scheduler",
    liveUrl: null,
    keyword: ["React", "PostgreSQL", "Express.js"],
  },
  {
    id: "5",
    title: "Jungle",
    description: "E-commerce store that supports Stripe payment",
    img: "/images/jungle.png",
    code: "https://github.com/MHassan47/Jungle",
    liveUrl: null,
    keyword: ["Ruby", "Rails", "PostgreSQL"],
  },
  {
    id: "6",
    title: "Passwordle",
    description: "Wordle inspired game",
    img: "/images/passwordle_loser.PNG",
    code: "https://github.com/MHassan47/PassWordle",
    liveUrl: "https://passwordle.netlify.app/",
    keyword: ["React"],
  },
  {
    id: "7",
    title: "Map it",
    description: "Collaborative, interactive map",
    img: "/images/map_it.PNG",
    code: "https://github.com/MHassan47/Wikimaps",
    liveUrl: null,
    keyword: ["JQuery", "Ajax", "Express.js", "PostgreSQL"],
  },
  {
    id: "8",
    title: "React-Weather",
    description: "Weather App ",
    img: "/images/san_francisco_weather.PNG",
    liveUrl: null,
    code: "https://github.com/MHassan47/React-Weather-App",
    keyword: ["React", "REST API"],
  },
];

export default portfolio;
