const portfolio = [
  {
    id: "0",
    title: "Realty",
    description:
      "A mobile real estate app where users can browse postings and message owners",
    img: "/images/realty_mockup.JPG",
    liveUrl: null,
    code: "https://github.com/MHassan47/realty",
    keyword: [
      "React Native",
      "TypeScript",
      "Redux",
      "Firestore",
      "TailwindCSS",
    ],
  },
  {
    id: "2",
    title: "Clinic",
    description: "A Health app where professionals track activities ",
    img: "/images/clinic_light.JPG",
    liveUrl: null,
    code: "https://github.com/MHassan47/clinic",
    keyword: ["React", "TypeScript", "TailwindCSS"],
  },
  {
    id: "3",
    title: "Workable",
    description: "A board where users create, save or search for jobs ",
    img: "/images/workable_home.JPG",
    liveUrl: null,
    code: "https://github.com/MHassan47/Workable",
    keyword: [
      "React",
      "TypeScript",
      "GraphQL",
      "Node.js",
      "Postgres",
      "TypeORM",
      "TailwindCSS",
    ],
  },
  {
    id: "4",
    title: "Budget App",
    description: "A budgeting app that lets users track their finances",
    img: "/images/budget_dashboard.JPG",
    liveUrl: null,
    code: "https://github.com/MHassan47/Budget-App",
    keyword: ["React", "MongoDB", "Redux", "Node.js", "MUI"],
  },
  {
    id: "5",
    title: "Produc_Div",
    description: "Collaborative productivity management app",
    img: "/images/dashboard.PNG",
    code: "https://github.com/MHassan47/Produc_Div",
    liveUrl: null,
    keyword: ["React", "PostgreSQL", "Node.js", "Express.js", "WebSocket"],
  },
  {
    id: "6",
    title: "Scheduler",
    description: "Real-Time interview scheduler",
    img: "/images/mainpage.png",
    code: "https://github.com/MHassan47/Scheduler",
    liveUrl: null,
    keyword: ["React", "PostgreSQL", "Express.js"],
  },
  {
    id: "7",
    title: "Jungle",
    description: "E-commerce store that supports Stripe payment",
    img: "/images/jungle.png",
    code: "https://github.com/MHassan47/Jungle",
    liveUrl: null,
    keyword: ["Ruby", "Rails", "Postgres"],
  },
  {
    id: "8",
    title: "Passwordle",
    description: "Wordle inspired game",
    img: "/images/passwordle_loser.PNG",
    code: "https://github.com/MHassan47/PassWordle",
    liveUrl: "https://passwordle.netlify.app/",
    keyword: ["React"],
  },
  {
    id: "9",
    title: "Map it",
    description: "Collaborative, interactive map",
    img: "/images/map_it.PNG",
    code: "https://github.com/MHassan47/Wikimaps",
    liveUrl: null,
    keyword: ["JQuery", "Ajax", "Express.js", "Postgres"],
  },
  {
    id: "10",
    title: "React-Weather",
    description: "Weather App ",
    img: "/images/san_francisco_weather.PNG",
    liveUrl: null,
    code: "https://github.com/MHassan47/React-Weather-App",
    keyword: ["React", "REST API"],
  },
];

export default portfolio;
